Repository gluster/glusto-tests, pull requests merged in 2021-06, with the labels that each got.

#71 [Test] Add test to validate replica eager-lock and volume profile
  tests/functional/afr/test_replica_eager_lock.py
Labels: Test

#74 [Test-Fix] Add distribute replica as part of tc
  tests/functional/afr/test_replica_eager_lock.py
Labels: Testfix

#73 [Test] - Check self heal with data-self-heal-algorithm set to full
  tests/functional/afr/test_self_heal_with_full_algorithm.py
Labels: Test

#76 [LibFix] Remove getchildren from get_volume_list as deprecated
  glustolibs-gluster/glustolibs/gluster/volume_ops.py
Labels: Libfix

#75 [LibFix] Removing getchildren from glustolibs as deprecated
  glustolibs-gluster/glustolibs/gluster/heal_ops.py
  glustolibs-gluster/glustolibs/gluster/peer_ops.py
  glustolibs-gluster/glustolibs/gluster/profile_ops.py
  glustolibs-gluster/glustolibs/gluster/quota_ops.py
  glustolibs-gluster/glustolibs/gluster/rebalance_ops.py
  glustolibs-gluster/glustolibs/gluster/snap_ops.py
  glustolibs-gluster/glustolibs/gluster/volume_libs.py
  glustolibs-gluster/glustolibs/gluster/volume_ops.py
Labels: Libfix
